<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Label:
            id: my_label
            text: "0% progress"

        ProgressBar:
            id: my_progress_bar
            # set default value
#            value: .25
            value: 0
            min: 0
            max: 1
            pos_hint: {'x':.1}
            size_hint_x: .8

        Button:
            text: 'Press me!'
            on_press: root.press_it()
