<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        paddinng: 10
        spacing: 10

        Label:
            text: "Name"
        TextInput:
            multiline: False
        Label:
            text: "Favorite Pizza"
        TextInput:
            multiline: False
        Button:
            text: "submit"
        Button:
            text: "clear"
        Button:
            text: "submit"