<MyLayout>
    BoxLayout
        orientation: "vertical"
        size: root.width, root.height

        Label:
            id: click_label
            text: "Favorite pizza below"
            font_size: 32

        Spinner:
            id: spinner_id
            text: "Favorite Pizza"
            values: ['papperoni', 'cheese', 'Mushroom']

            on_text: root.spinner_clicked(spinner_id.text)
        Label:
            text: ''


