<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Label:
            id: my_label
            font_size: 32
            text: "The switch is on!"
        Switch:
            id: my_switch
#            active: True
            active: False
#            disabled: True
            disabled: False
            font_size: 32
            on_active: root.switch_click(self, self.active)