# inherit the color properties
<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        Carousel:
            direction: "top"

            Image:
                source: "D://Kivy/Tutorial_12/Image/Itnesh.jpg"
            Image:
                source: "D://Kivy/file/flower.jpeg"
            Image:
                source: "D://Kivy/file/Mountain.jpg"
